# Generated by Django 2.2.14 on 2022-05-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
